name: 'todo-xzentrix'

static-env:
  HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous

user-env:
  PG_DATABASE_URL:
    description: 'Postgres database URL'
    mandatory: true
  NEXTJS_SERVER_URL:
    default: 'http://localhost:3000'
    description: 'Next.js Server URL for authentication and custom business logic'
    mandatory: true
  HASURA_GRAPHQL_JWT_SECRET:
    default: '{"key": "7BF4wrE6bN60vGmz4K4eTIbk0iZs4bdNdPVALfrVWUq4FZK3hll99HTbHF0kK6uD","type": "HS256"}'
    description: 'JWT Secret key'
    mandatory: true